cedimagen/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paciente/$', 'citas_medicas.views.paciente'),
    url(r'^cita/$', 'citas_medicas.views.cita'),

    url(r'^chaining/', include('smart_selects.urls')),
    # -------------------------------------------------------------------------------------
    # AJAX
    # -------------------------------------------------------------------------------------
    url(r'^ajax_tipo/$', 'citas_medicas.views.ajax_tipo'),
    url(r'^ajax_grupo/$', 'citas_medicas.views.ajax_grupo'),
    url(r'^ajax_especialidad/$', 'citas_medicas.views.ajax_especialidad'),
    url(r'^ajax_lista_doctor/$', 'citas_medicas.views.ajax_lista_doctor'),
    # -------------------------------------------------------------------------------------
    # AJAX
    # -------------------------------------------------------------------------------------
    url(r'^pdf_registro/$', 'citas_medicas.views.pdf_registro'),
]

citas_medicas/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from models import Paciente, Cita
from datetime import date

class PacienteForm(ModelForm):
    class Meta:
        model = Paciente
        # fields = '__all__'
        fields = ['nombres','apellidos','telefono_fijo','telefono_celular','direccion','referencia','foto','fecha_nacimiento',]
        labels = {
            'fecha_nacimiento': ('Fecha de Nacimiento'),
        }
        widgets = {
            'direccion': Textarea(attrs={'rows': 3}),
            'referencia': Textarea(attrs={'rows': 3}),
        }

class CitaForm(forms.Form):
    # tipo = forms.ChoiceField(label='Tipo', choices=(('', 'Seleccione'),))
    # grupo = forms.ChoiceField(label='Grupo', choices=(('', 'Seleccione'),))
    # especialidad = forms.ChoiceField(label='Especialidad', choices=(('', 'Seleccione'),))
    tipo = forms.IntegerField(label='Tipo', widget=forms.Select())
    grupo = forms.IntegerField(label='Grupo', widget=forms.Select())
    especialidad = forms.IntegerField(label='Especialidad', widget=forms.Select())
    # fecha = forms.DateField(label='Fecha de Consulta', input_formats=['%d/%m/%Y'], initial=date.today)
    fecha = forms.DateField(label='Fecha de Consulta', input_formats=['%d/%m/%Y'])
    # fecha = forms.DateField(label='Fecha de Consulta')
    doctor_horario = forms.IntegerField(label='Doctor Horario')

cedimagen/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<!--[if gt IE 8]> <html class="ie9" lang="en"> <![endif]-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    <title>DEMO</title>

    <!--<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic' rel='stylesheet' type='text/css'>-->
    <link href="{% static 'css/jquery-ui-1.10.3.custom.css' %}" rel="stylesheet" />
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/blue.css' %}" id="style-switch" />

    <!-- REVOLUTION BANNER CSS SETTINGS -->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'rs-plugin/css/settings.css' %}" media="screen" />-->

    <!--[if IE 9]>
        <link rel="stylesheet" type="text/css" href="{% static 'css/ie9.css' %}"/>
        <![endif]-->

    <!--<link rel="icon" type="image/png" href="{% static 'images/fevicon.png' %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/inline.min.css' %}" /></head>

<body>
    <div class="container">
        <div class="row">
        <!--About-us top-content-->
        {% block content %}
            Default content ...
        {% endblock content %}
        </div>
    </div>

    <!--JS Inclution-->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-new/js/bootstrap.min.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script>-->
    <!--<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.sticky.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.flexisel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.imedica.min.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'js/custom-imedicajs.min.js' %}"></script>-->
    {% block script %}
    {% endblock script %}
</body>
</html>

cedimagen/templates/test1.html
{% load dajaxice_templatetags %}
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Blog</title>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.dajax.core.js' %}"></script>
    {% dajaxice_js_import %}
    <script type="text/javascript">
        function my_callback(data){
            alert(data.message);
        }
    </script>
</head>
<body>
<input type="button" onclick="Dajaxice.citas_medicas.dajaxice_example(my_callback)" value="Get message from server!">
</body>
</html>

cedimagen/templates/test_form.html
<!--<tr>-->
    <!--<th><label for="id_tipo">Tipo grupo:</label></th>-->
    <!--<td>ls<input type="text" name="tipo" id="id_tipo" /></td>-->
<!--</tr>-->
{% load static %}
<link href="{% static 'css/tester.css' %}" rel="stylesheet" media="screen">
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>